### ISSUE TITLE
공지사항과 예약 알림을 분리해주실 수 있나요?

### ISSUE THREAD

**Issue by HyunsDev** [jonghokim27/ssutoday#2]
예약에 필요하여 알림을 사용하고는 있지만 원하지 않은 공지사항 알림도 함께 표시되서 불편한 부분이 있습니다.

알림 옵션을 세분화해서 종류별로 알림을 분리하는 건 어떠신가요?

**Comment by jonghokim27** [comment]
다음 업데이트에 반영하겠습니다.
의견 주셔서 감사합니다.

**Comment by jonghokim27** [comment]
2.2.0 업데이트에 반영되었습니다.

**Comment by HyunsDev** [comment]
감사합니다 :)
